version: "3"

services:
  bc-postgres:
    container_name: bc-postgres-1
    image: postgres
    env_file:
      - images/postgres/.env
    ports:
      - 5432:5432
    networks:
      - sce
    volumes:
      - bc-postgres-data:/var/lib/postgresql/data
    restart: always

  bc-redis:
    container_name: bc-redis-1
    image: redis
    ports:
      - 6379:6379
    networks:
      - bc
    volumes:
      - bc-redis:/data
    restart: always

networks:
  bc:
    driver: "bridge"

volumes:
  bc-postgres-data:
  bc-redis:
