name: Base Repo Sync

on:
  push:
    branches: [ base ]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "dtrodger/TC-CICD-Demo"
          source_branch: "base"
          destination_repo: "dtrodger/TC-CICD-Demo-Sync"
          destination_branch: "main"