name: QA CICD Deploy

on:
  push:
    branches: [ qa ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv env
        source env/bin/activate
        pip install -r requirements.txt
    - name: Generate the Lambda deployment package
      run: |
        source env/bin/activate
        zappa package -o exed.zip
    - name: Deploy to Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: exed-cicd-2-qa-dev
        zip_file: exed.zip
        memory_size: 128
        timeout: 10
        handler: handler.lambda_handler
        role: arn:aws:iam::642030467107:role/exed-cicd-2-qa-dev-ZappaLambdaExecutionRole
        runtime: python3.8
