name: Base Repo Sync

on:
  push:
    branches: [ base ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: net-engine/github-repository-sync-action@v1
        with:
          ssh_private_key: ${{ secrets.SSHKEY }}
          target_repo_url: git@github.com:dtrodger/TC-CICD-Demo-Sync.git