name: Base Repo Sync

on:
  push:
    branches: [ base ]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:dtrodger/TC-CICD-Demo.git"
          source_branch: "base"
          destination_repo: "git@github.com/dtrodger/TC-CICD-Demo-Sync.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSHKEY }}